version: "2.4"
services:
  category-service:
    build: ./category-service
    ports:
      - 9081:9081
    depends_on:
      - naming-server
      - ajustadoati-db

  # Gateway
  api-gateway:
    build: ./api-gateway
    depends_on:
      - naming-server
    ports:
      - 9080:9080

  # Mysql
  ajustadoati-db:
    build: ./mysql
    volumes:
      - /Users/richardroj/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Dexter876.
      - MYSQL_DATABASE=task
    ports:
      - 3306:3306

  # Eureka Server
  naming-server:
    build: ./naming-server
    ports:
      - 9061:9061

