logging:
  level:
    root: INFO
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9061/eureka}

spring:
  cloud:
    gateway:
      routes:
        - id: category-service-route
          uri: ${category-service}
          predicates:
            - Path=/suite/category-service/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs